// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230210123138_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140),
                            Description = "Admin",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140),
                            Description = "Intake",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140),
                            Description = "Manager",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6140)
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserStatusId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6180),
                            Email = "",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6180),
                            PasswordHash = "FC57D856266390FBEFE1E3BF64011C538A3CB25C4D048F867998351335F744059D6EB133A85FECC9B2A60088147EDDA18622FA95B3282C30BAAFABC0E1EA9A9D",
                            PasswordSalt = "4A46744489B84AF9679B72BC470BC9401887A7CC2AA76D44CB450197BC05AC04633047A90949826784CD545CFA0885267FA8C1C9AE1918086D92DBC0FB5D64D7",
                            UserStatusId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6190),
                            Email = "",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6190),
                            PasswordHash = "FC57D856266390FBEFE1E3BF64011C538A3CB25C4D048F867998351335F744059D6EB133A85FECC9B2A60088147EDDA18622FA95B3282C30BAAFABC0E1EA9A9D",
                            PasswordSalt = "4A46744489B84AF9679B72BC470BC9401887A7CC2AA76D44CB450197BC05AC04633047A90949826784CD545CFA0885267FA8C1C9AE1918086D92DBC0FB5D64D7",
                            UserStatusId = 1,
                            Username = "all"
                        });
                });

            modelBuilder.Entity("Server.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6330),
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6330),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6350),
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6350),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6370),
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6370),
                            RoleId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6390),
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 256, DateTimeKind.Utc).AddTicks(6390),
                            RoleId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Server.Models.UserStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("UserStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5250),
                            Description = "Active",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5260)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5260),
                            Description = "Pending",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5260)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5260),
                            Description = "Locked",
                            ModifiedDate = new DateTime(2023, 2, 10, 12, 31, 38, 255, DateTimeKind.Utc).AddTicks(5260)
                        });
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.HasOne("Server.Models.UserStatus", "UserStatus")
                        .WithMany()
                        .HasForeignKey("UserStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("Server.Models.UserRole", b =>
                {
                    b.HasOne("Server.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
